# Generated by Django 4.2.26 on 2026-01-05 13:17

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0095_fix_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledshape',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='labeledshape',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeledshape',
            name='view_id',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dimension',
            field=models.CharField(choices=[('3d', 'DIM_3D'), ('2d', 'DIM_2D'), ('multiview', 'MULTIVIEW')], default=cvat.apps.engine.models.DimensionType['DIM_2D'], max_length=16),
        ),
        migrations.CreateModel(
            name='MultiviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('part_number', models.IntegerField()),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiview_data', to='engine.data')),
                ('video_view1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiview_view1', to='engine.video')),
                ('video_view2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiview_view2', to='engine.video')),
                ('video_view3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiview_view3', to='engine.video')),
                ('video_view4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiview_view4', to='engine.video')),
                ('video_view5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiview_view5', to='engine.video')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
