# Generated by Django 4.2.26 on 2026-01-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0096_labeledshape_description_labeledshape_needs_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='engine.data'),
        ),
    ]
