# Generated by Django 4.2.26 on 2026-01-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0097_alter_video_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledtrack',
            name='view_id',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
