# Generated by Django 4.2.26 on 2026-01-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0099_multiviewdata_variable_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiviewdata',
            name='original_files',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
